export const SET_USER = "SET_USER";
export const UNSET_USER = "UNSET_USER";

export const LOADING = "LOADING";

export const SET_RECOMMENDED_RECIPES = "SET_RECOMMENDED_RECIPES";
export const SET_RECIPES = "SET_RECIPES";

export const SET_CURRENT_RECIPE = "SET_CURRENT_RECIPE";
export const UNSET_CURRENT_RECIPE = "UNSET_CURRENT_RECIPE";

export const SET_RECIPE_DETAIL = "SET_RECIPE_DETAIL";
export const UNSET_RECIPE_DETAIL = "UNSET_RECIPE_DETAIL";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const UNSET_INGREDIENTS = "UNSET_INGREDIENTS";
export const SET_INSTRUCTIONS = "SET_INSTRUCTIONS";
export const UNSET_INSTRUCTIONS = "UNSET_INSTRUCTIONS";

export const SET_FAVORITES = "SET_FAVORITES";
export const SET_SHOPPING_LIST  = "SET_SHOPPING_LIST";
export const SET_DB_INGREDIENTS  = "SET_DB_INGREDIENTS";
